export const filtersData = [
  // {
  //   name: "Высоты",
  //   options: [{ unit: "GEO" }, { unit: "MEO" }, { unit: "LEO" }],
  //   type: "checkbox",
  //   id: "UNApogee",
  // },
  {
    name: "Страны",
    options: [],
    type: "checkbox-scroll",
    id: "state",
    dropdown: "Выбор страны",
    placeholder: "Введите страну",
  },
  {
    name: "Года",
    options: [],
    type: "checkbox-scroll",
    id: "ldateyear",
    dropdown: "Выбор года",
    placeholder: "Введите год",
  },
  {
    name: "Орбиты",
    options: [],
    type: "checkbox-scroll",
    id: "oporbitoqu",
    dropdown: "Выбор орбиты",
    placeholder: "Введите орбиту",
  },
  {
    name: "Статусы",
    options: [],
    type: "checkbox-scroll",
    id: "status",
    dropdown: "Выбор статуса",
    placeholder: "Введите статус",
  },
  {
    name: "Имена",
    options: [],
    type: "checkbox-scroll",
    id: "name",
    dropdown: "Выбор имени",
    placeholder: "Введите имя",
  },
  {
    name: "Типы",
    options: [],
    type: "checkbox-scroll",
    id: "type",
    dropdown: "Выбор типа",
    placeholder: "Введите тип",
  },
];
