export const TableCodes = {
  state: {
    RU: "Россия и СССР",
    J: "Япония",
    US: "США",
    CN: "Китай",
    IN: "Индия",
    I: "Италия",
    UK: "Великобритания",
    F: "Франция",
    "I-ESA": "Европейское космическое агенство",
    CA: "Канада",
    D: "Германия",
  },
  oporbitoqu: {
    "GEO/D  -": "GEO/D",
    "GEO/ID -": "GEO/ID",
    "GEO/S  -": "GEO/S",
    "GTO    -": "GTO",
    "HEO    -": "HEO",
    "HEO/M  -": "HEO/M",
    "LEO/I  -": "LEO/I",
    "LEO/P  -": "LEO/P",
    "LEO/S  -": "LEO/S",
    "LLEO/I -": "LLEO/I",
    "LLEO/P -": "LLEO/P",
    "LLEO/S -": "LLEO/S",
    "MEO    -": "MEO/S",
    "CLO    -": "CLO",
    "EEO    -": "EEO",
    "LEO/R  -": "LEO/R",
    "LLEO/I S": "LLEO/I S",
    "LLEO/R -": "LLEO/R",
    "VHEO   -": "VHEO",
  },
};
